#!/usr/bin/env sysbench
-- Copyright (C) 2021 Oracle

-- ----------------------------------------------------------------------
-- INSERT INTO ... SELECT   OLTP benchmark
-- ----------------------------------------------------------------------

require("oltp_common")

sysbench.cmdline.commands.prepare = {
   function ()
      if (not sysbench.opt.auto_inc) then
         -- Create empty tables on prepare when --auto-inc is off, since IDs
         -- generated on prepare may collide later with values generated by
         -- sysbench.rand.unique()
         sysbench.opt.table_size=200000000
      end

      cmd_prepare()
   end,
   sysbench.cmdline.PARALLEL_COMMAND
}

function prepare_statements()
   -- We do not use prepared statements here, but oltp_common.sh expects this
   -- function to be defined
end

function event()
   local table_num = sysbench.rand.uniform(1, sysbench.opt.tables)
   local table_name = "sbtest" .. table_num
   -- INSERT into the next table up, numerically. If we're at the last table, INSERT into the first
   local table_name2 = (table_num == sysbench.opt.tables) and "sbtest1" or "sbtest" .. (table_num + 1)
   local k_val = sysbench.rand.default(1, (sysbench.opt.table_size - sysbench.opt.range_size + 1))
   local k_valend = k_val + sysbench.opt.range_size - 1

   con:query(string.format("INSERT INTO %s (id, k, c, pad) SELECT " ..
                           "null,k,c,pad from %s where id between %i AND %i",
                           table_name, table_name2, k_val, k_valend))
end
